CREATE TABLE pelatih (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nama_club TEXT NOT NULL,
  nama_pelatih TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);